<a href="https://colab.research.google.com/github/junanote/test_python1/blob/master/210707_1_python_language.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

In [26]:
np.__version__


'1.19.5'

In [87]:
def onehotcylinder(cylinders):
    if cylinders == 3:
      cylinder = np.array([1,0,0,0,0])    #넘파이로 만듬 
    elif cylinders == 4:
      cylinder = np.array([0,1,0,0,0])
    elif cylinders == 5:
      cylinder = np.array([0,0,1,0,0])
    elif cylinders == 6:
      cylinder = np.array([0,0,0,1,0])
    else : # 8
      cylinder = np.array([0,0,0,0,1])
    return cylinder

In [39]:
displacement = 307.0
horsepower =130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1 

## if cylinders = 8, origin = 1   --> onehot encoding
import numpy as np
if cylinders == 3:
  cylinder = np.array([1,0,0,0,0])    #넘파이로 만듬 
elif cylinders == 4:
  cylinder = np.array([0,1,0,0,0])
elif cylinders == 5:
  cylinder = np.array([0,0,1,0,0])
elif cylinders == 6:
  cylinder = np.array([0,0,0,1,0])
else : # 8
  cylinder = np.array([0,0,0,0,1])

x_continus = np.array([displacement, horsepower, weight, accel])
# cylinder = np.array([0,0,0,0,1])

cylinder = np.array([0,0,0,0,1]) # 8
org = np.array([1,0,0]) # 1

In [28]:
type(x_continus), type(cylinder), type(org)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [34]:
# np.concatenate((a, b), axis=None)
result = np.concatenate((x_continus,cylinder,org), axis=None)
result.shape, result

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [35]:
# [307.0,130.0, 3504.0, 12.0, 0,0,0,0,1]
# result.reshape(1,12)
result = result.reshape(-1, result.size)
result, result.shape

(array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]),
 (1, 12))

In [37]:
result

array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]])

# function 이해


In [42]:
21 + 14

35

In [43]:
32 + 45

77

In [47]:
def sum():
  first = 32
  second = 45
  result = first + second
  result  
  return result

In [48]:
sum()

77

In [50]:
f01 = 32
s02 = 21
def sum(f01, s02):    #파라메터 - 외부에서 호출할때 중요한거 순서 (이름은 중요하지 않음, 내부에서는 이름 중요) 
  first = s02
  second = f01
  result = first + second
  result  
  return result

In [54]:
sum(32,21), sum(3,2), sum(21,564)

(53, 5, 585)

In [55]:
21 * 32 * 2


1344

In [56]:
31 * 63 * 41

80073

In [88]:
def tim(f01,f02,f03):
  first = f01
  second =f02
  third = f03
  result = first * second * third
  return result

In [90]:
tim(21,32,2), tim(31,63,41)

(1344, 80073)

In [80]:
#def differencdVars(*var01, *args02)
def diffparam(*var_list, **var_dict):
  print(var_dict)
  result01 = len(var_list)
  return result01

In [81]:
 diffparam(1,2,3, a=2, b=3)

{'a': 2, 'b': 3}


3

In [83]:
 diffparam(1,2,3,5,6,  c=2, d=3, a=2, b=3)

{'c': 2, 'd': 3, 'a': 2, 'b': 3}


5